"""create_trains_stations_tables

Revision ID: de74356fb0dc
Revises: 47851b64d0c5
Create Date: 2026-07-15 08:55:04.706819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de74356fb0dc'
down_revision = '47851b64d0c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_code', sa.String(length=10), nullable=False),
    sa.Column('station_name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('platform_count', sa.Integer(), nullable=False),
    sa.Column('operational_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stations_station_code'), ['station_code'], unique=True)

    op.create_table('trains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_code', sa.String(length=20), nullable=False),
    sa.Column('train_name', sa.String(length=100), nullable=False),
    sa.Column('train_type', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('carriage_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_maintenance_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trains_train_code'), ['train_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trains_train_code'))

    op.drop_table('trains')
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stations_station_code'))

    op.drop_table('stations')
    # ### end Alembic commands ###
