"""create_infrastructure_and_audit_tables

Revision ID: f6800a7a8ef7
Revises: 153caba72246
Create Date: 2026-07-15 13:30:25.400893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6800a7a8ef7'
down_revision = '153caba72246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('infrastructure_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.String(length=30), nullable=False),
    sa.Column('instance_name', sa.String(length=100), nullable=False),
    sa.Column('instance_type', sa.String(length=20), nullable=False),
    sa.Column('image_id', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('terminated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('infrastructure_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_infrastructure_instances_instance_id'), ['instance_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('infrastructure_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_infrastructure_instances_instance_id'))

    op.drop_table('infrastructure_instances')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
